updating CMakeLists.txt, missing <set> include in term_manager_intern…
SRI-CSL/sally pull request #71
Opened 2024-12-19 07:41 UTC by karthiknukala

…al.h

2024-12-19 23:46 UTC, ahmed-irfan requested changes

2024-12-19 23:46 UTC, ahmed-irfan commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall")
can you paste here the warning you are getting

2024-12-19 23:50 UTC, karthiknukala commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall")
`/Users/e35480/git/sally/src/engine/pdkind/reachability.cpp:118:15: warning: variable 'check' set but not used [-Wunused-but-set-variable]
  for (size_t check = 0; !reachability_obligations.empty(); ++ check) {
              ^
1 warning generated.`

2024-12-20 01:04 UTC, ahmed-irfan approved these changes
LGTM

2024-12-20 01:05 UTC, merged